### ISSUE TITLE
[PE-D][Tester B] Confusing documentation for help command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-4/tp#128]
![image.png](https://raw.githubusercontent.com/Heart-of-N1/ped/main/files/3284fc88-b66d-4922-8a75-e21e7b24c851.png)
Over here, month is expected to be inputted via JAN, FEB format but users may confuse it with numbers.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Heart-of-N1/ped#3

**Comment by HengShuHong** [comment]
Updated UG to have a pointer to state that Month is in MMM format
