### ISSUE TITLE
[PE-D][Tester A] App crashes when attempting command 'total_profit'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-4/tp#149]
App crashed due to null pointer exception when 'total_profit' was inputted.

![bruh.png](https://raw.githubusercontent.com/CerealMiller/ped/main/files/11a254cd-707a-4430-8e1c-a2e2229282bb.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: CerealMiller/ped#4

**Comment by LowTL** [comment]
Issue resolved.
