### ISSUE TITLE
[PE-D][Tester C] Bugs encountered after one item is sold out

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-4/tp#151]
![](url)
![image.png](https://raw.githubusercontent.com/ZhangWenyue3325/ped/main/files/239ab3f3-73f8-4f7b-8129-0c159960500e.png)

After selling out all the bananas, the bestseller command failed.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ZhangWenyue3325/ped#6

**Comment by LowTL** [comment]
Issue resolved.
