### ISSUE TITLE
[PE-D][Tester D] Program crashes after using total_profit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T15-4/tp#162]
I'm not sure why but inputting the `total_profit` command after selling an item, the program crashes.

![image.png](https://raw.githubusercontent.com/rismm/ped/main/files/de8b580a-ba86-42c5-bd7d-a85b948007e9.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: rismm/ped#9

**Comment by LowTL** [comment]
Unable to replicate issue, seems to work fine on my end: 

![image](https://github.com/AY2324S2-CS2113-T15-4/tp/assets/110801908/d4ab8f8d-6c70-4ec5-94c7-8075de9847fe)

**Comment by LowTL** [comment]
Issue resolved.
